# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TaskTui < Formula
  desc "Terminal user interface for Task"
  homepage "https://github.com/aleksandersh/task-tui/"
  version "0.0.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/aleksandersh/task-tui/releases/download/v0.0.3/task-tui_darwin_amd64.tar.gz"
      sha256 "82c9c03750f516930e06713b718eb766b2964abb72344ccd4a69e3e28f20a40e"

      def install
        bin.install "task-tui"
      end
    end
    on_arm do
      url "https://github.com/aleksandersh/task-tui/releases/download/v0.0.3/task-tui_darwin_arm64.tar.gz"
      sha256 "4b1994311ea735f1c1d06247d778a0b9246d66e76ed4272e4f80315f45f1fd37"

      def install
        bin.install "task-tui"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aleksandersh/task-tui/releases/download/v0.0.3/task-tui_linux_amd64.tar.gz"
        sha256 "94c02d2cdd6a6b54062e04cb763c94631bbd6a1b145aa200fd06b37bccc28e56"

        def install
          bin.install "task-tui"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/aleksandersh/task-tui/releases/download/v0.0.3/task-tui_linux_arm.tar.gz"
        sha256 "eb1d35a2a9f67c6db444a95954e3f1321efd57418d50f6333f0fe5fe5a046680"

        def install
          bin.install "task-tui"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aleksandersh/task-tui/releases/download/v0.0.3/task-tui_linux_arm64.tar.gz"
        sha256 "6e33a9b405545198480980b085d05f87a31a4058cd9e2ce368910deec21a0e6f"

        def install
          bin.install "task-tui"
        end
      end
    end
  end

  test do
    system "#{bin}/task-tui --version"
  end
end
