# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TaskTui < Formula
  desc "Terminal user interface for Task"
  homepage "https://github.com/aleksandersh/task-tui/"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aleksandersh/task-tui/releases/download/v1.2.0/task-tui_darwin_amd64.tar.gz"
      sha256 "83bb6738fe575942c6845156a462158d3d364aaa44827f3a7941dbe518f0ca65"

      def install
        bin.install "task-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aleksandersh/task-tui/releases/download/v1.2.0/task-tui_darwin_arm64.tar.gz"
      sha256 "7eea9d190bf3ad7cd4623b1b69802723676034440d01d54063912aa01144ef54"

      def install
        bin.install "task-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/aleksandersh/task-tui/releases/download/v1.2.0/task-tui_linux_amd64.tar.gz"
      sha256 "1c55e2ca1be683b67ca3a4484ec6dc7293f0e470b29d32554e4fbabbbfb68c33"
      def install
        bin.install "task-tui"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/aleksandersh/task-tui/releases/download/v1.2.0/task-tui_linux_arm.tar.gz"
      sha256 "3dd35c6aa5e8b217b9863845cb762d6a95291a33230e826920ed8485a4cb5595"
      def install
        bin.install "task-tui"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/aleksandersh/task-tui/releases/download/v1.2.0/task-tui_linux_arm64.tar.gz"
      sha256 "5e37467fe1fcd2fc4deb32c7eb9c7cbed3c43ed9f4361323ee547d685050a479"
      def install
        bin.install "task-tui"
      end
    end
  end

  test do
    system "#{bin}/task-tui --version"
  end
end
